
language: node_js

sudo: required

node_js:
  - "6.9"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libstdc++-4.9-dev
      - openssl
env:
  - CXX=g++-4.9

before_install:
  - npm install -g npm@latest
  - npm install -g truffle
  - npm install -g ganache-cli


install:
  - npm install 

script:
- ganache-cli -p 8545 > /dev/null &
- sleep 5
- truffle migrate --network development

