version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: npm install --no-optional
      - run: 
          name: Install truffle
          command: npm install truffle
      - run: 
          name: Compile Contracts
          command: truffle compile
